In [1]:
# importing necessary lib

import pandas as pd
import numpy as np

ann = pd.read_csv(r"F:\carreer\\adultKNN.csv") # loading the data

pd.set_option('display.max_rows',500) # to get output of record till 500

# Data Cleaning and Preprocessing

In [2]:
ann.head() # taking overview of dataset

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [3]:
ann.shape # rows and cols

(48842, 15)

In [4]:
ann.isnull().sum() # checking the nulls

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

# To replace "?"

In [5]:
ann=ann.replace({'?':np.nan})

In [6]:
ann.isnull().sum()

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

In [7]:
#ann.rename(columns={'marital-status':'marital_status','native-country':'native_country'},inplace=True)

In [8]:
ann.occupation .value_counts()

Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: occupation, dtype: int64

In [9]:
ann.workclass = ann.workclass.fillna("Private")
ann.occupation = ann.occupation.fillna("Other_services")
ann['native-country'] = ann['native-country'] .fillna("United-States")

In [10]:
ann.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder # importing necessary lib
le = LabelEncoder()

In [12]:
ann.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18    Private  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4     Other_services    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [13]:
ann.workclass = le.fit_transform(ann.workclass)
ann['marital-status'] = le.fit_transform(ann['marital-status'])
ann.relationship = le.fit_transform(ann.relationship)
ann.occupation = le.fit_transform(ann.occupation)
ann.race = le.fit_transform(ann.race)
ann.gender = le.fit_transform(ann.gender)
ann['native-country'] = le.fit_transform(ann['native-country'])


In [14]:
ann = ann.drop(['education'], axis=1)

In [15]:
ann.income.replace({"<=50K":0,">50K":1}, inplace= True)

# Data Sampling

In [16]:
from sklearn.model_selection import train_test_split # importing necessary lib

In [17]:
ann_train,ann_test=train_test_split(ann,test_size=.2)

In [18]:
ann_train_x = ann_train.iloc[:,0:-1]
ann_train_y = ann_train.iloc[:,-1]

In [19]:

ann_test_x = ann_test.iloc[:,0:-1]
ann_test_y = ann_test.iloc[:,-1]

In [20]:
print(ann_train_x.shape)
print(ann_train_y.shape)
print(ann_test_x.shape)
print(ann_test_y.shape)

(39073, 13)
(39073,)
(9769, 13)
(9769,)


# Apply KNN to build a model

In [21]:
# how to build the algrothem


# we import some fuction from sklearn
#we created an object
#run the fit fuction (it build the model) and while run your fit fuction the in put is x,y(x train ,y train)
#we did the perdiction

#run the confustion matrix

In [22]:
from sklearn.neighbors import KNeighborsClassifier # importing necessary lib

In [23]:
dt_ann= KNeighborsClassifier(n_neighbors=9)# taking the odd number

In [24]:
dt_ann.fit(ann_train_x,ann_train_y)

KNeighborsClassifier(n_neighbors=9)

In [25]:
pred= dt_ann.predict(ann_test_x)
pred

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [26]:
pred.shape

(9769,)

In [27]:
##run the confustion matrix

In [28]:
from sklearn.metrics import confusion_matrix # import necessary lib

In [29]:
tab_ann = confusion_matrix(ann_test_y, pred)
tab_ann # the confustion matrix is build

array([[7069,  359],
       [1702,  639]], dtype=int64)

In [30]:
#accuracy

from sklearn.metrics import accuracy_score

In [31]:
accuracy_score(ann_test_y,pred)*100

78.90265124373018

# Applying naive bayes Algorithm

In [32]:
from sklearn.naive_bayes import MultinomialNB # import necessary lib

In [33]:
nb_ann=MultinomialNB()

In [34]:
nb_ann.fit(ann_train_x,ann_train_y)

MultinomialNB()

In [35]:
pred_ann = nb_ann.predict(ann_test_x)

In [36]:
from sklearn.metrics import confusion_matrix 

In [37]:
tab_ann = confusion_matrix(ann_test_y ,pred_ann)

In [38]:
tab_ann # confution matrix

array([[7132,  296],
       [1783,  558]], dtype=int64)

# its performance is almost 0. its happening because it gives us the prediction on one x variable which has highest strong relationship to others x variables